spring:
  main:
    banner-mode: console
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcoursecluster.bkk5k.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=WebfluxCourseCluster
      # aqui o banco cria o indexador automático
      auto-index-creation: true
  application:
    name: webflux-course